apiVersion: v1
kind: Config
clusters:
- name: "project2"
  cluster:
    server: "https://50.17.157.68/k8s/clusters/c-m-xv988gvn"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0TVRRdwpOekkwT1RBZUZ3MHlNekEwTVRNeE56TTBNRGxhRncwek16QTBNVEF4TnpNME1EbGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZ3hOREEzTWpRNU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRTdYYU9XWm9leWVuQQpGeDlUTTZlblp4ZDhxSkgyK2MyL21FMTk2e\
      E5pK2U4UGEydG9VZVV4clRHK21kcE9vWi9MSDg2QzA1ejZiakpNClhBVEhHSVJVV2FOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      EFZZ2YzRVJ0RUlGcEFoaUJkUnBaYkhBcmRjTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEMgpWV\
      mxqMk9sUGdBM1dnRng4WkF0QWsxc3ZGSVlEWkRDTUJnd2ZIVGVkMndJZ0VUcTFmQkFZV1Njd1pwU\
      1BoeDRYClpCWGtBay9kZXdES3Q1bkhhUlpiYzM0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "project2"
  user:
    token: "kubeconfig-user-mrl2rrtfcj:5ndm6jhzpm5bhts28nvpc4mpxxr2pxcrtpphbbd54q227kf5sw4b88"


contexts:
- name: "project2"
  context:
    user: "project2"
    cluster: "project2"

current-context: "project2"
